@JWTAuth_HostAddress = https://localhost:7225

### Register User

POST {{JWTAuth_HostAddress}}/api/authentication/register-user
Content-Type: application/json

{
  "firstName": "Brian",
  "lastName": "Kemboi",
  "email": "bkemboi590@gmail.com",
  "userName": "kemboi590",
  "password": "Karibu@2024"
}

###  Register User
POST {{JWTAuth_HostAddress}}/api/authentication/register-user
Content-Type: application/json

{
  "firstName": "student",
  "lastName": "student",
  "email": "student@gmail.com",
  "userName": "student",
  "password": "Karibu@2024",
  "role": "Student"
}

### Register User

POST {{JWTAuth_HostAddress}}/api/authentication/register-user
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@gmail.com",
  "userName": "test",
  "password": "Karibu@2024",
  "role": "Student"
}

### Login User

POST {{JWTAuth_HostAddress}}/api/authentication/login-user
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Karibu@2024"
}

### Refresh Token

POST {{JWTAuth_HostAddress}}/api/authentication/refresh-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2VtYm9pNTkwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiZWM3NGNkYS1lMzc5LTRmMjgtODVkNC0xYWRmODcyZGY3N2QiLCJlbWFpbCI6ImJrZW1ib2k1OTBAZ21haWwuY29tIiwic3ViIjoiYmtlbWJvaTU5MEBnbWFpbC5jb20iLCJqdGkiOiJmY2M1ZjVkYy0yMTQwLTQyODEtOTNkNy0xOTI0MDk0OGU3NzUiLCJleHAiOjE3MzM5OTg0NzksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyMjUiLCJhdWQiOiJ1c2VyIn0.3m4oG_FLcNFAV20u2fSfXoIsrgZdM8TqJ_yLIZTFNMI",
  "refreshToken": "e0303ec5-31c9-4baf-aea6-5fb84adb8aad-ee61cda9-68fd-48a6-a8ff-d57babef3e3a"
  
}

### Main Home Page

GET {{JWTAuth_HostAddress}}/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDdkODZiMjItYTRkYy00MjZhLWFmYjctOGNkMWVlMjM5MmE4IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwianRpIjoiZDQ4ZDMxNjAtYTRlMy00Yzg0LTkxYjAtNWM1YWMwYjA4MjhkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTczNDE4NzMyNiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.owi7UtPiAk7r2UWAbwcAK6a15XfAQeoxG-ay1LZLF_U
### Get Manager's page

GET {{JWTAuth_HostAddress}}/management
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDdkODZiMjItYTRkYy00MjZhLWFmYjctOGNkMWVlMjM5MmE4IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwianRpIjoiNGE4MzBhZWMtMDY3NS00NWNkLWI5MjMtOTQ3NTdlY2ZkZGNkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTczNDE4Njg5MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.OcoSYN5MwbT5_UK9sSuoYUYDP_iybBUNGzLg1FGMvwQ

### Get Student's page

GET {{JWTAuth_HostAddress}}/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDdkODZiMjItYTRkYy00MjZhLWFmYjctOGNkMWVlMjM5MmE4IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwianRpIjoiNDNiNzAyOTYtZDQwOC00Y2UwLTk2MTUtMDgwNGQ5ZjdlYTQ0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTczNDE4NjY2NCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.Xau9jM7LsThhUHFpCxJ8Ey3FW1O-k7L5ZZZBBzHUtmk

### Get Student's home page

GET {{JWTAuth_HostAddress}}/home/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDdkODZiMjItYTRkYy00MjZhLWFmYjctOGNkMWVlMjM5MmE4IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwianRpIjoiNDNiNzAyOTYtZDQwOC00Y2UwLTk2MTUtMDgwNGQ5ZjdlYTQ0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTczNDE4NjY2NCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.Xau9jM7LsThhUHFpCxJ8Ey3FW1O-k7L5ZZZBBzHUtmk

### Get Manager's home page

GET {{JWTAuth_HostAddress}}/home/manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDdkODZiMjItYTRkYy00MjZhLWFmYjctOGNkMWVlMjM5MmE4IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwianRpIjoiNDNiNzAyOTYtZDQwOC00Y2UwLTk2MTUtMDgwNGQ5ZjdlYTQ0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTczNDE4NjY2NCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.Xau9jM7LsThhUHFpCxJ8Ey3FW1O-k7L5ZZZBBzHUtmk
