@JWTAuth_HostAddress = https://localhost:7225

### Register User

POST {{JWTAuth_HostAddress}}/api/authentication/register-user
Content-Type: application/json

{
  "firstName": "Brian",
  "lastName": "Kemboi",
  "email": "bkemboi590@gmail.com",
  "userName": "kemboi590",
  "password": "Karibu@2024"
}

###  Register User
POST {{JWTAuth_HostAddress}}/api/authentication/register-user
Content-Type: application/json

{
  "firstName": "kemboi",
  "lastName": "kemboi",
  "email": "kemboi@gmail.com",
  "userName": "kemboi",
  "password": "Karibu@2024",
  "role": "Student"
}

### Register User

POST {{JWTAuth_HostAddress}}/api/authentication/register-user
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@gmail.com",
  "userName": "test",
  "password": "Karibu@2024",
  "role": "Student"
}

### Login User

POST {{JWTAuth_HostAddress}}/api/authentication/login-user
Content-Type: application/json

{
  "email": "manager@gmail.com",
  "password": "Karibu@2024"
}

### Refresh Token

POST {{JWTAuth_HostAddress}}/api/authentication/refresh-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFuYWdlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMzA0NzhkZTMtMWFiMy00ZjEzLWFjM2UtMmY1ZjQyMDBhZjk0IiwiZW1haWwiOiJNYW5hZ2VyQGdtYWlsLmNvbSIsInN1YiI6Ik1hbmFnZXJAZ21haWwuY29tIiwianRpIjoiMTY0NWRiZTYtODdmNi00ODFjLWE5MzUtYzJlMWQ5M2NmOTZlIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWFuYWdlciIsImV4cCI6MTczNDI4MjczMCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.QsXyQGPSpOUSBTshS1YcDJQ0xeEifXmQ0Rc749v0WFE",
  "refreshToken": "7edb82a5-36c0-4836-a349-012e0c36ddb7-2fa08853-31e9-4c0f-8860-8b46777611aa" 

}

### Main Home Page

GET {{JWTAuth_HostAddress}}/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFuYWdlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMzA0NzhkZTMtMWFiMy00ZjEzLWFjM2UtMmY1ZjQyMDBhZjk0IiwiZW1haWwiOiJNYW5hZ2VyQGdtYWlsLmNvbSIsInN1YiI6Ik1hbmFnZXJAZ21haWwuY29tIiwianRpIjoiNDRhYWI5YjYtY2IxNy00MjZhLTk2MWYtNTMxYmIxNDIyODFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWFuYWdlciIsImV4cCI6MTczNDI4Mjc5OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.3lK2f6Zu1g4SkZZ7K9qNxXO0quoEGAb_Ze-Q-wILAMk

### Get Manager's page

GET {{JWTAuth_HostAddress}}/management
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFuYWdlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMzA0NzhkZTMtMWFiMy00ZjEzLWFjM2UtMmY1ZjQyMDBhZjk0IiwiZW1haWwiOiJNYW5hZ2VyQGdtYWlsLmNvbSIsInN1YiI6Ik1hbmFnZXJAZ21haWwuY29tIiwianRpIjoiNDRhYWI5YjYtY2IxNy00MjZhLTk2MWYtNTMxYmIxNDIyODFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWFuYWdlciIsImV4cCI6MTczNDI4Mjc5OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.3lK2f6Zu1g4SkZZ7K9qNxXO0quoEGAb_Ze-Q-wILAMk


### Get Student's page

GET {{JWTAuth_HostAddress}}/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2VtYm9pIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI2MzgxNzQwMy04YTBkLTQ5NGYtOTBiNi1hYWY0NTc0NGFhM2YiLCJlbWFpbCI6ImtlbWJvaUBnbWFpbC5jb20iLCJzdWIiOiJrZW1ib2lAZ21haWwuY29tIiwianRpIjoiMDg5YjMzN2EtNDU0Zi00MDJmLTgxOWYtNDY0MzIxNjk2ZmU5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTczNDI4MjYwNCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.rK2LVGMcFystC1ETXxT9cOiHOuyUD0yJl51hqaWQFyc

### Get Student's home page

GET {{JWTAuth_HostAddress}}/home/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2VtYm9pIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI2MzgxNzQwMy04YTBkLTQ5NGYtOTBiNi1hYWY0NTc0NGFhM2YiLCJlbWFpbCI6ImtlbWJvaUBnbWFpbC5jb20iLCJzdWIiOiJrZW1ib2lAZ21haWwuY29tIiwianRpIjoiMDg5YjMzN2EtNDU0Zi00MDJmLTgxOWYtNDY0MzIxNjk2ZmU5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTczNDI4MjYwNCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.rK2LVGMcFystC1ETXxT9cOiHOuyUD0yJl51hqaWQFyc

### Get Manager's home page

GET {{JWTAuth_HostAddress}}/home/manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFuYWdlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMzA0NzhkZTMtMWFiMy00ZjEzLWFjM2UtMmY1ZjQyMDBhZjk0IiwiZW1haWwiOiJNYW5hZ2VyQGdtYWlsLmNvbSIsInN1YiI6Ik1hbmFnZXJAZ21haWwuY29tIiwianRpIjoiNDRhYWI5YjYtY2IxNy00MjZhLTk2MWYtNTMxYmIxNDIyODFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWFuYWdlciIsImV4cCI6MTczNDI4Mjc5OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIyNSIsImF1ZCI6InVzZXIifQ.3lK2f6Zu1g4SkZZ7K9qNxXO0quoEGAb_Ze-Q-wILAMk
